name = "mixpoint"
type = 'javascript'
account_id = '7e1d0afce2e42ff7e7d7ea364664051c'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
site = {bucket = "./dist",entry-point = "workers-site"}
